# ==============================================================================
# HEADER: src/physics/run_worker_wrapper.py
# ==============================================================================
# Description:
#   Unified entry point for parallel execution via joblib.
#   Acts as a dispatcher that routes the compute task to the appropriate 
#   physics generation engine (Hadronic or Quark) based on the task tuple.
#
# Cleaned & Refactored:
#   - Removed unused imports.
#   - Standardized docstrings for clarity.
# ==============================================================================

from src.physics.worker_hadronic_gen import worker_hadronic_gen
from src.physics.worker_quark_gen import worker_quark_gen

def run_worker_wrapper(task_tuple, baselines):
    """
    Dispatches the compute task to the specific physics generator.
    
    Parameters:
    - task_tuple: Tuple containing (mode, batch_size, seed, batch_idx).
    - baselines: Dictionary of hadronic maximum masses (Required for Hadronic mode).
                 Passed as read-only shared memory in parallel contexts.
    
    Returns:
    - List of valid star data points generated by the worker.
    """
    # Unpack task metadata
    mode, batch_size, seed, batch_idx = task_tuple
    
    # Dispatch to the correct physics engine
    if mode == 'hadronic':
        # Hadronic generation requires baseline masses for homologous scaling logic
        return worker_hadronic_gen(batch_size, baselines, seed, batch_idx)
    
    else:
        # Quark generation is purely parametric (Generalized CFL)
        # It does not rely on the hadronic baselines
        return worker_quark_gen(batch_size, seed, batch_idx)